### ISSUE TITLE
Checkout repos using https versus ssh

### ISSUE THREAD

**Issue by cal4** [NerdWalletOSS/shepherd#820]
Port 22 on my network is firewalled, so checking out via ssh doesn't work (this [workaround](https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port) doesn't work either).

It'd be nice if shepherd supported checking out via https. AFAIK this isn't supported at the moment. Ideally whether shepherd uses https or ssh would be configurable.

Here's a snippet of the error when running `shepherd checkout .`:
```
➜  shepherd git:(7-25-2024-replace-gvs-redis-passwords) ✗ shepherd checkout .
✔ Loaded 72 repos

[GM-DBT/CVC_162609_veh-audio-management-ops] 1/72
GitError: Cloning into '/home/cal/.shepherd/2024-07-25-replace-gvs-redis-names/repos/GM-DBT/CVC_162609_veh-audio-management-ops'...
kex_exchange_identification: Connection closed by remote host
Connection closed by 140.82.112.35 port 443
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (/home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:1451:25)
    at PluginStore.exec (/home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:1500:29)
    at /home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:1927:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:1925:16)
    at GitExecutorChain.<anonymous> (/home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:1909:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/cal/.nvm/versions/node/v20.15.0/lib/node_modules/@nerdwallet/shepherd/node_modules/simple-git/dist/cjs/index.js:52:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  task: {
    commands: [
      'clone',
      '--depth',
      '1',
      'git@github.com:GM-DBT/CVC_162609_veh-audio-management-ops.git',
      '/home/cal/.shepherd/2024-07-25-replace-gvs-redis-names/repos/GM-DBT/CVC_162609_veh-audio-management-ops'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
```

**Comment by cal4** [comment]
This should be handled by #748
